---
- name: create_domain | template
  template:
    dest: "/tmp/htpc.xml"
    src: "vm.xml.j2"

- name: create_domain | define
  command: "virsh define /tmp/htpc.xml"

- name: define virtual machines
  virt:
    name: htpc
    command: define
    xml: "{{ lookup('template', 'vm.xml.j2') }}"
    autostart: true

- name: start virtual machines
  virt:
    name: htpc
    state: running
  when: start_vms
