---
- name: create_domain | template
  template:
    src: vm.xml.j2
    dest: /tmp/htpc.xml
  tags:
    - define_htpc

- name: create_domain | define
  command: "virsh define /tmp/htpc.xml"
  tags:
    - define_htpc

- name: define virtual machines
  virt:
    name: htpc
    command: define
    xml: "{{ lookup('template', 'vm.xml.j2') }}"
    autostart: true
  tags:
    - define_htpc

- name: start virtual machines
  virt:
    name: htpc
    state: running
  when: start_vms
