---
- name: enable hugepages in qemu
  lineinfile:
    dest: /etc/default/qemu-kvm
    regexp: "^KVM_HUGEPAGES="
    line: "KVM_HUGEPAGES=1"
  become: true

- name: assign hugepages
  become: true
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      vm.nr_hugepages=2200
      kernel.shmmax=4613734400
      vm.hugetlb_shm_group=36
  notify: reload-sysctl