---
- name: install required packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - seabios
    - qemu-utils
    - hugepages
    - bridge-utils
    - libvirt
    - libvirt-python
    - python-virtinst

- name: prepare system configuration for IGP passthrough
  include: prepare-system.yml
  tags: prepare_system

- name: enable hugepages
  include: enable-hugepages.yml
  when: enable_hugepages

- name: download virtio drivers for windows
  include: download-virtiowin.yml
  tags: download_virtiowin