---
- name: install required packages
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if force_update else 'present'}}"
  loop:
    - qemu-kvm
    - seabios
    - qemu-utils
    - hugepages
    - libvirt-bin
    - virtinst
    - python-libvirt
    - libguestfs-tools

- name: prepare system configuration for IGP passthrough
  import_tasks: prepare-system.yml
  tags: prepare_system

- name: enable hugepages
  import_tasks: enable-hugepages.yml
  tags: enable_hugepages

- name: download virtio drivers for windows
  import_tasks: download-virtiowin.yml
  tags: download_virtiowin