---
- name: install required packages
  apt: pkg={{ item }} state=present
  with_items:
    - qemu-kvm
    - seabios
    - qemu-utils
    - hugepages
    - bridge-utils

- name: prepare system configuration for IGP passthrough
  include: prepare-system.yml
  when: not system_prepared
  tags: prepare_system

- name: enable hugepages
  include: enable-hugepages.yml
  when: enable_hugepages

- name: create folder for virtio-win drivers
  file:
    dest: /opt/virtio-win/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: download virtio-win drivers
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
    dest: /opt/virtio-win/
    owner: root
    group: root
    mode: 0775
  tags: virtiodrivers

- name: bring startup script in place
  copy:
    src: home/caphm/start-win10vm.sh
    dest: /home/caphm/start-win10vm.sh
    owner: caphm
    group: caphm
    mode: 0755