---
- name: install required packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - qemu-kvm
    - seabios
    - qemu-utils
    - hugepages
    - bridge-utils
    - libvirt-bin
    - virtinst
    - python-libvirt

- name: prepare system configuration for IGP passthrough
  include_tasks: prepare-system.yml
  tags: prepare_system

- name: enable hugepages
  include_tasks: enable-hugepages.yml
  when: enable_hugepages

- name: download virtio drivers for windows
  include_tasks: download-virtiowin.yml
  tags: download_virtiowin