---
- name: update /etc/default/grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"'
  become: true
  register: grubfile

- name: update grub
  command: sudo update-grub
  become: true
  when: grubfile|changed