---
- name: enable iommu and turn off efifb in GRUB_CMDLINE
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on video=efifb:off"'
  become: true
  notify: update-grub

- name: blacklist default IGP driver kernel modules
  become: true
  blockinfile:
    dest: /etc/modprobe.d/blacklist.conf
    backup: yes
    block: |
      # blacklist vga drivers for IGP to allow passthrough to VM
      blacklist snd_hda_intel
      blacklist snd_hda_codec_hdmi
      blacklist i915
  notify: update-initramfs

- name: assign vfio driver to PCIe devices
  become: true
  blockinfile:
    dest: /etc/modprobe.d/vfio.conf
    backup: yes
    create: yes
    block: |
      options vfio-pci ids=8086:0412,8086:0c0c
  notify: update-initramfs

- name: add ignore_msrs option to kvm.conf
  become: true
  blockinfile:
    dest: /etc/modprobe.d/kvm.conf
    backup: yes
    create: yes
    block: |
      options kvm ignore_msrs=1
  notify: update-initramfs

- name: update list of modules in initramfs
  become: true
  blockinfile:
    dest: /etc/initramfs-tools/modules
    backup: yes
    create: yes
    block: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
      vhost-net
      kvm
      kvm_intel
  notify: update-initramfs

- name: apply apparmor workaround for libvirt USB passthrough
  become: true
  blockinfile:
    dest: /etc/apparmor.d/abstractions/libvirt-qemu
    backup: yes
    create: yes
    block: |
      # Workaround for USB passthrough
      /dev/bus/usb/ r,
      /etc/udev/udev.conf r,
      /sys/bus/ r,
      /sys/class/ r,
      /run/udev/data/ r,
  notify: update-initramfs