---
- name: update /etc/default/grub
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on video=efifb:off"'
    #line: 'GRUB_CMDLINE_LINUX_DEFAULT="rd.driver.pre=vfio-pci quiet splash intel_iommu=on iommu=pt video=efifb:off"'
  become: true
  notify: update-grub

- name: blacklist default IGP drivers
  become: true
  blockinfile:
    dest: /etc/modprobe.d/blacklist.conf
    backup: yes
    block: |
      # blacklist vga drivers for IGP to allow passthrough to VM
      blacklist snd_hda_intel
      blacklist snd_hda_codec_hdmi
      blacklist i915

- name: add placeholder vfio drivers
  become: true
  blockinfile:
    dest: /etc/modprobe.d/vfio.conf
    backup: yes
    create: yes
    block: |
      options vfio-pci ids=8086:0412,8086:0c0c

- name: add ignore_msrs option to kvm.conf
  become: true
  blockinfile:
    dest: /etc/modprobe.d/kvm.conf
    backup: yes
    create: yes
    block: |
      options kvm ignore_msrs=1

- name: update list of modules in initramfs
  become: true
  blockinfile:
    dest: /etc/initramfs-tools/modules
    backup: yes
    create: yes
    block: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
      vhost-net
      kvm
      kvm_intel
  notify: update-initramfs