---
- set_fact:
    apphome: "{{appdata}}/onedrive"

- name: Create apphome directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755

- name: Copy configuration
  copy:
    src: "onedrive.conf"
    dest: "{{apphome}}/config"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755

- name: Create sync_list
  blockinfile:
    create: yes
    marker: ""
    path: "{{apphome}}/sync_list"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
    block: |
      Bilder/Alben
      Musik
      Videos

- name: upload the onedrive Dockerfile to the docker host
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/build/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
  with_items:
    - Dockerfile
    - entrypoint.sh

- name: Start docker app onedrive
  docker_service:
    project_name: onedrive
    state: present
    build: "{{update_dockers}}"
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        onedrive:
          build: "{{apphome}}/build"
          container_name: onedrive
          hostname: onedrive
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{apphome}}:/config"
            - "{{arraypath}}/media:/onedrive"
          environment:
            - ONEDRIVE_UID={{defaultuser.uid}}
            - ONEDRIVE_GID={{defaultuser.maingid}}
