---
- name: Prepare onedrive instances
  include_tasks: prepare-instance.yml
  with_items: "{{onedrives}}"

- set_fact:
    compose_dir: /tmp/docker-compose/

- name: Create temp dir for compose file
  file:
    dest: "{{compose_dir}}"
    state: directory

- name: Template out onedrive compose file to host
  template:
    src: onedrive.yml
    dest: "{{compose_dir}}/docker-compose.yml"

- name: Start docker app onedrive-client
  docker_service:
    project_name: onedrive-client
    state: present
    pull: "{{update_dockers}}"
    project_src: "{{compose_dir}}"
  register: startup_output

- debug:
    var: startup_output

- name: Cleanup temp dir
  file:
    dest: "{{compose_dir}}"
    state: absent