---
# ansible-playbook dev.yml -i hosts --tags docker_apps -K
# the binary | this.file | -i targets | *optional --tags | -K asks for sudo pass

- hosts: dev
  become: true

  roles:
    - docker
    - docker-compose
    - mergerfs
    - snapraid
    - zeus
