# ansible-playbook production.yml -i hosts --tags docker_apps
---
- hosts: production
  become: true
  roles:
    - { role: "print-server", tags: "print_server" }
    - { role: "htpc", tags: "htpc" }
    - { role: "kodi-alexa-skillhost", tags: "kodi-alexa" }
    - { role: "media-server", tags: "media-server" }
    - { role: "teamspeak-server", tags: "teamspeak-server" }
    - { role: "onedrive-client", tags: "onedrive-client" }
    - { role: "nginx-reverse-proxy", tags: "nginx-reverse-proxy" }
