# ansible-playbook production.yml -i hosts --tags docker_apps
---
- hosts: production
  become: true
  roles:
    - docker
    - docker-compose
    - mergerfs
    - snapraid
    - vm-host
    - print-server
    - zeus
