# ansible-playbook production.yml -i hosts --tags docker_apps
---
- hosts: production
  become: true
  roles:
    - { role: "docker", tags: ["baseconf"] }
    - { role: "docker-compose", tags: ["baseconf"] }
    - { role: "mergerfs", tags: ["baseconf", "mergerfs"] }
    - { role: "snapraid", tags: ["baseconf", "snapraid"] }
    - { role: "zeus", tags: ["baseconf"] }
    - { role: "vm-host", tags: ["vm-host", "virtual-machines"] }
    - { role: "media-server", tags: ["media-server", "docker-apps"] }
    - { role: "teamspeak-server", tags: ["teamspeak-server", "docker-apps"] }
    - { role: "nginx-reverse-proxy", tags: ["nginx-reverse-proxy", "docker-apps"] }
    - { role: "mosquitto", tags: ["mosquitto", "docker-apps"] }
    - { role: "home-assistant", tags: ["home-assistant", "docker-apps"] }
    # - { role: "print-server", tags: "print-server" }
    # - { role: "lirc", tags: "lirc" }
    # - { role: "kodi-repo", tags: "kodi-repo" }
    # - { role: "htpc", tags: ["htpc", "virtual-machines"] }
    # - { role: "kodi-alexa-skillhost", tags: ["kodi-alexa", "docker-apps"] }
    # - { role: "onedrive-client", tags: ["onedrive-client", "docker-apps"] }
