# ansible-playbook production.yml -i hosts --tags docker_apps
---
- hosts: production
  become: true
  roles:
    - { role: "docker", tags: "docker" }
    - { role: "docker-compose", tags: "docker_compose" }
    - { role: "mergerfs", tags: "mergerfs" }
    - { role: "snapraid", tags: "snapraid" }
    - { role: "vm-host", tags: "vm_host" }
    - { role: "print-server", tags: "print_server" }
    - { role: "zeus", tags: "zeus" }
