---
- name: install packages
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if force_update else 'present'}}"
  loop:
    - lirc
    - lirc-x
    - alsa
    - alsa-utils

- name: Put configuration files into place
  copy:
    src: "{{item}}"
    dest: /etc/lirc/
    owner: root
    group: root
    mode: 0644
  loop:
    - lirc_options.conf
    - hardware.conf
  notify:
    - restart lircd

- name: Put remote configurations into place
  copy:
    src: "{{item}}"
    dest: /etc/lirc/lircd.conf
    owner: root
    group: root
    mode: 0644
  loop:
    - samsung-tv.conf
  notify:
    - restart lircd