---
- name: install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - lirc
    - lirc-x
    - alsa-base
    - alsa-utils

- name: Put configuration files into place
  copy:
    src: "{{item}}"
    dest: /etc/lirc/
    owner: root
    group: root
    mode: 0644
  with_items:
    - lirc_options.conf
    - hardware.conf
  notify:
    - restart lircd

- name: Put remote configurations into place
  copy:
    src: "{{item}}"
    dest: /etc/lirc/lircd.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - samsung-tv.conf
  notify:
    - restart lircd