---
- name: install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - lirc
    - lirc-x

- name: Put configuration files into place
  file:
    src: "{{item}}"
    dest: /etc/lirc/
    owner: root
    group: root
    mode: 0644
  with_items:
    #- lirc_options.conf
    - hardware.conf
  notify:
    - restart lircd

- name: Put remote configurations into place
  file:
    src: "{{item}}"
    dest: /etc/lirc/lircd.conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - samsung-tv.conf
  notify:
    - restart lircd