---
version: '2'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    volumes:
      - /home/docker/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM="claim-mR3rarVobeNjsf6ccs4q"
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ="Europe/Berlin"
      - ALLOWED_NETWORKS="192.168.1.0/24"
