---
- name: Create appdata directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

- name: Download configuration files from github
  git:
    repo: https://github.com/caphm/hass-config.git
    dest: /tmp/hass-config

- name: Install configuration files
  copy:
    src: "/tmp/hass-config"
    dest: "{{apphome}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  notify: docker restart home-assistant

- name: Install secrets
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - secrets.yaml
    - known_devices.yaml
  notify: docker restart home-assistant

- name: Install secret images
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/www/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - anna.jpg
    - cpm.jpg

- name: Download customizer component files from github
  git:
    repo: https://github.com/andrey-git/home-assistant-customizer.git
    dest: /tmp/hass-customizer-component

- name: Install customizer component
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/custom_components/customizer"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_fileglob:
    - /tmp/hass-customizer-component/customizer/*
  notify: docker restart home-assistant
