- name: Download configuration files from github
  git:
    repo: https://github.com/caphm/hass-config.git
    dest: /tmp/home-assistant

- name: Install configuration files
  synchronize:
    src: "/tmp/home-assistant"
    dest: "{{appdata}}/"
    recursive: yes
  notify: docker restart home-assistant

- name: Install secrets
  copy:
    src: "{{item}}"
    dest: "{{hass_home}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  loop:
    - secrets.yaml
    # - known_devices.yaml
  notify: docker restart home-assistant

- name: Install secret images
  copy:
    src: "{{item}}"
    dest: "{{hass_home}}/www/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  loop:
    - anna.jpg
    - cpm.jpg
