---
- name: Create appdata directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

- name: Download configuration files from github
  git:
    repo: https://github.com/caphm/hass-config.git
    dest: /tmp/hass-config

- name: Install configuration files
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_fileglob:
    - /tmp/hass-config/*
  notify: docker restart home-assistant

- name: Install package configuration files
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/packages"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_fileglob:
    - /tmp/hass-config/packages/*
  notify: docker restart home-assistant

- name: Install custom components for switch platform
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/custom_components/switch/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_fileglob:
    - /tmp/hass-config/custom_components/switch/*
  notify: docker restart home-assistant

- name: Install secrets
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - secrets.yaml
    - known_devices.yaml
  notify: docker restart home-assistant

- name: Install images
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/www/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - anna.jpg
    - cpm.jpg

# - name: Install customUI update script
#   get_url:
#     url: https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/update.sh?raw=true
#     dest: "{{apphome}}/update.sh"
#     owner: "{{defaultuser.uid}}"
#     group: "{{defaultuser.maingid}}"
#     mode: 0755

# - name: Install/Update customUI
#   shell: "{{apphome}}/update.sh"

- name: Download customizer component files from github
  git:
    repo: https://github.com/andrey-git/home-assistant-customizer.git
    dest: /tmp/hass-customizer-component

- name: Install customizer component
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/custom_components/customizer"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_fileglob:
    - /tmp/hass-customizer-component/customizer/*
  notify: docker restart home-assistant
