---
- set_fact:
    apphome: "{{appdata}}/home-assistant"

- name: Create appdata directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

# - name: Install configuration files
#   template:
#     src: "{{item}}"
#     dest: "{{apphome}}/{{item}}"
#     owner: "{{defaultuser.uid}}"
#     group: "{{defaultuser.maingid}}"
#     mode: 0644
#   with_items:
#     - configuration.yaml
#     - groups.yaml
#     - customize.yaml

- name: Start docker app home-assistant
  docker_service:
    project_name: home-assistant
    state: present
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        hass-relay:
          image: tynor88/socat
          container_name: hass-relay
          hostname: hass-relay
          user: "{{defaultuser.uid}}"
          restart: always
          network_mode: bridge
          ports:
            - "18123:18123"
          environment:
            - LISTEN_PORT=18123
            - FORWARD_PORT=8123
            - VIRTUAL_HOST=smarthome.caphm.de
            - VIRTUAL_PORT=18123
            - "LETSENCRYPT_HOST={{letsencrypt_domains}}"
            - "LETSENCRYPT_EMAIL={{email_address}}"
        home-assistant:
          image: homeassistant/home-assistant
          container_name: home-assistant
          hostname: home-assistant
          user: "{{defaultuser.uid}}"
          restart: always
          volumes:
            - "{{apphome}}:/config"
          network_mode: host
          environment:
            - TZ=Europe/Berlin
