---
- set_fact:
    apphome: "{{appdata}}/home-assistant"
    appdaemon_apphome: "{{appdata}}/home-assistant/appdaemon"
    hadockermon_home: "{{appdata}}/home-assistant/ha-dockermon"
  tags:
    - conf_hass

# - name: Configure home-assistant
#   import_tasks: configure.yml
#   tags:
#     - conf_hass

- name: Start docker app home-assistant
  docker_service:
    project_name: home-assistant
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        home-assistant:
          image: homeassistant/home-assistant
          container_name: home-assistant
          hostname: home-assistant
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{hass_home}}:/config"
          network_mode: host
          environment:
            - TZ=Europe/Berlin
        hass-relay:
          image: tynor88/socat
          container_name: hass-relay
          hostname: home-assistant
          restart: always
          networks:
            web:
              aliases:
                - home-assistant
            iot:
              aliases:
                - home-assistant
          environment:
            - LISTEN_PORT=8123
            - FORWARD_PORT=8123
          labels:
            traefik.enable: "true"
            traefik.frontend.rule: "Host:{{ home_assistant_url }}"
            traefik.docker.network: "web"
            traefik.port: "8123"
        appdaemon:
          image: acockburn/appdaemon:latest
          container_name: appdaemon
          hostname: appdaemon
          stdin_open: true
          restart: always
          volumes:
            - /etc/localtime:/etc/localtime:ro
            - "{{appdaemon_home}}:/conf"
          networks:
            - iot
          environment:
            - "HA_URL=http://home-assistant:8123"
            - "TOKEN={{appdaemon_token}}"
        ha-dockermon:
          image: philhawthorne/ha-dockermon
          container_name: ha-dockermon
          hostname: ha-dockermon
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{hadockermon_home}}:/config"
            - /var/run/docker.sock:/var/run/docker.sock
          networks:
            - iot
          ports:
            - "8126:8126"
      networks:
        iot:
          name: iot
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.18.1.0/24
        web:
          external:
            name: web
