---
- set_fact:
    apphome: "{{appdata}}/home-assistant"

- name: Create appdata directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

- name: Install configuration files from github repo
  git:
    repo: https://github.com/caphm/hass-config.git
    dest: "{{apphome}}"
    force: yes

- name: Install secrets
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - secrets.yaml
    - known_devices.yaml

- name: Start docker app home-assistant
  docker_service:
    project_name: home-assistant
    state: present
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        hass-relay:
          image: tynor88/socat
          container_name: hass-relay
          hostname: hass-relay
          restart: always
          network_mode: bridge
          ports:
            - "18123:18123"
          environment:
            - LISTEN_PORT=18123
            - FORWARD_PORT=8123
            - VIRTUAL_HOST=smarthome.caphm.de
            - VIRTUAL_PORT=18123
            - "LETSENCRYPT_HOST={{letsencrypt_domains}}"
            - "LETSENCRYPT_EMAIL={{email_address}}"
        home-assistant:
          image: homeassistant/home-assistant
          container_name: home-assistant
          hostname: home-assistant
          user: "{{defaultuser.uid}}"
          restart: always
          volumes:
            - "{{apphome}}:/config"
          network_mode: host
          environment:
            - TZ=Europe/Berlin
