---
- set_fact:
    apphome: "{{appdata}}/home-assistant"
  tags:
    - configure_home_assistant

- name: Configure home-assistant
  include_tasks: configure.yml
  tags:
    - configure_home_assistant

- name: Start docker app home-assistant
  docker_service:
    project_name: home-assistant
    state: present
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        hass-relay:
          image: tynor88/socat
          container_name: hass-relay
          hostname: hass-relay
          restart: always
          network_mode: bridge
          ports:
            - "18123:18123"
          environment:
            - LISTEN_PORT=18123
            - FORWARD_PORT=8123
            - VIRTUAL_HOST=smarthome.caphm.de
            - VIRTUAL_PORT=18123
            - "LETSENCRYPT_HOST={{letsencrypt_domains}}"
            - "LETSENCRYPT_EMAIL={{email_address}}"
        home-assistant:
          image: homeassistant/home-assistant
          container_name: home-assistant
          hostname: home-assistant
          user: "{{defaultuser.uid}}"
          restart: always
          volumes:
            - "{{apphome}}:/config"
            - "{{apphome}}/uhttpd.crt:/usr/share/ca-certificates/gateway.residenz.caphm.de.crt"
          network_mode: host
          environment:
            - TZ=Europe/Berlin
            - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

- name: update ca-certificates in container - add container to inventory
  add_host:
    name: home-assistant
    ansible_connection: docker
  changed_when: false

- name: update ca-certificates in container
  delegate_to: home-assistant
  become: true
  raw: update-ca-certificates