- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300
  when: force_update

- name: install packages
  apt:
    name: "{{ packages }}"
    state: "{{ 'latest' if force_update else 'present' }}"
  vars:
    packages:
     - bash-completion
     - curl
     - exiftool
     - fuse
     - glances
     - git
     - htop
     - iftop
     - iotop
     - jq
     - lynx
     - mc
     - ncdu
     - nmap
     - openssh-server
     - python3
     - reptyr
     - screen
     - smartmontools
     - sudo
     - tmux
     - tree
     - wget
     - bluez

- name: Ensure Ansible ist up to date
  pip:
    name: ansible
    state: "{{ 'latest' if force_update else 'present' }}"

- name: create main group for default user
  group:
    name: "{{defaultuser.maingroup}}"
    gid: "{{defaultuser.maingid}}"
    state: present
    system: no

- name: create default user
  user:
    uid: "{{defaultuser.uid}}"
    name: "{{defaultuser.name}}"
    group: "{{defaultuser.maingroup}}"
    groups: "{{defaultuser.groups}}"
    state: present
    system: no
    append: yes

- name: disable swapping
  become: true
  blockinfile:
    dest: /etc/sysctl.conf
    block: vm.swappiness=1
  notify: reload-sysctl
