---
# Users & groups
defaultuser:
  name: caphm
  uid: 1000
  maingroup: caphm
  maingid: 1000
  groups:
    - sudo

appdata: "/home/{{defaultuser.name}}/appdata"

email_address: nope
gmail_pass: nope
