- name: Create teamspeak-server appdata directory
  file:
    dest: "{{ teamspeak_home }}"
    state: directory
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"
    mode: 0755

- name: Start docker app teamspeak-server
  docker_service:
    project_name: teamspeak-server
    state: present
    pull: "{{ force_update }}"
    definition:
      version: '3'
      services:
        teamspeak:
          image: aheil/teamspeak3-server
          container_name: teamspeak
          hostname: teamspeak
          stdin_open: true
          tty: true
          user: "{{ defaultuser.uid }}"
          restart: always
          volumes:
            - "{{ teamspeak_home }}:/data"
            - "/etc/timezone:/etc/timezone:ro"
          networks:
            web:
              ipv4_address: "{{ macvlannetworks.web.static_ips.teamspeak }}"
          environment:
            - "TS3SERVER_LICENSE=accept"

      networks:
        web:
          external:
            name: web
