---
- name: install packages required by docker-compose
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools

- name: Download pip install script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0755
    owner: root
    group: root

- name: Install pip
  command: python /tmp/get-pip.py

- name: Installing docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present
