- name: Create appdata directory for Unifi
  file:
    path: "{{ unifi_home }}"
    state: directory
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"

- name: Create docker networks
  docker_network:
    name: "{{ item.key }}"
    state: present
    driver: bridge
    ipam_driver: default
    ipam_options:
      subnet: "{{ item.value.subnet }}"
  loop: "{{ networks|dict2items }}"

- name: Start docker service unifi
  docker_service:
    project_name: unifi
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        controller:
          image: "jacobalberty/unifi:stable"
          container_name: unifi
          hostname: unifi
          stdin_open: true
          tty: true
          restart: always
          network_mode: host
          volumes:
            - "{{ unifi_home }}:/unifi"
          environment:
            - "TZ=Europe/Berlin"
            - "RUNAS_UID0=false"
            - "UNIFI_UID={{ defaultuser.uid }}"
            - "UNIFI_GID={{ defaultuser.maingid }}"

        relay:
          image: tynor88/socat
          container_name: unifi-relay
          hostname: unifi-relay
          restart: always
          networks:
            web:
              aliases:
                - unifi
          environment:
            - LISTEN_PORT=8443
            - FORWARD_PORT=8443
          labels:
            traefik.enable: "true"
            traefik.docker.network: "web"
            traefik.port: "8443"
            traefik.protocol: "https"
            traefik.frontend.passHostHeader: "true"
            traefik.fqdn.frontend.rule: "Host:{{ unifi_host }}"
            traefik.frontend.headers.SSLRedirect: "true"
            traefik.frontend.headers.STSSeconds: 315360000
            traefik.frontend.headers.browserXSSFilter: "true"
            traefik.frontend.headers.contentTypeNosniff: "true"
            traefik.frontend.headers.forceSTSHeader: "true"
            traefik.frontend.headers.SSLHost: "caphm.de"
            traefik.frontend.headers.STSIncludeSubdomains: "true"
            traefik.frontend.headers.STSPreload: "true"
            traefik.frontend.headers.frameDeny: "true"
