- name: Create appdata directory for Unifi
  file:
    path: "{{ unifi_home }}"
    state: directory
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"

- name: Create docker networks
  docker_network:
    name: "{{ item.key }}"
    state: present
    driver: bridge
    ipam_driver: default
    ipam_options:
      subnet: "{{ item.value.subnet }}"
  loop: "{{ networks|dict2items }}"

- name: Start docker service unifi
  docker_service:
    project_name: unifi
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        controller:
          image: "jacobalberty/unifi:stable"
          container_name: unifi
          hostname: unifi
          stdin_open: true
          tty: true
          restart: always
          network_mode: host
          volumes:
            - "{{ unifi_home }}/data:/unifi/data"
            - "{{ unifi_home }}/log:/unifi/log"
            - "{{ private_domain_cert }}:/unifi/cert/cert.pem:ro"
            - "{{ private_domain_key }}:/unifi/cert/privkey.pem:ro"
          environment:
            - "TZ=Europe/Berlin"
            - "RUNAS_UID0=false"
            - "UNIFI_UID={{ defaultuser.uid }}"
            - "UNIFI_GID={{ defaultuser.maingid }}"
            - "CERT_IS_CHAIN=true"
