- name: Create appdata directory for Unifi
  file:
    path: "{{ unifi_home }}"
    state: directory
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"

- name: Create macvlan networks
  docker_network:
    name: "{{ item.value.name }}"
    state: present
    driver: macvlan
    driver_options:
      parent: "{{ item.value.parent }}"
    ipam_driver: default
    ipam_options:
      subnet: "{{ item.value.subnet }}"
      gateway: "{{ item.value.gateway }}"
      iprange: "{{ item.value.iprange }}"
  loop: "{{ macvlannetworks | dict2items }}"

- name: Create docker bridge networks
  docker_network:
    name: "{{ item.value.name }}"
    state: present
    driver: bridge
    driver_options:
      "com.docker.network.bridge.name": "br-docker-{{ item.value.name }}"
    ipam_driver: default
    ipam_options:
      subnet: "{{ item.value.subnet }}"
  loop: "{{ bridgenetworks | dict2items }}"

# - name: Isolate docker bridge networks from LAN
#   iptables:
#     state: present
#     action: insert
#     chain: INPUT
#     source: "{{ item.value.subnet }}"
#     destination: 192.168.1.0/24
#     jump: DROP
#   loop: "{{ bridgenetworks | dict2items }}"

# - name: Allow Home Assistant access to LAN
#   iptables:
#     state: present
#     action: insert
#     chain: INPUT
#     source: "{{ bridgenetworks.traefik_backend.static_ips.home_assistant }}"
#     destination: 192.168.1.0/24
#     jump: ACCEPT
  

- name: Start docker service unifi
  docker_service:
    project_name: unifi
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        controller:
          image: "jacobalberty/unifi:stable"
          container_name: unifi
          hostname: unifi
          stdin_open: true
          tty: true
          restart: always
          networks:
            homelan:
              ipv4_address: "{{ bridgenetworks.homelan.static_ips.unifi }}"
          volumes:
            - "{{ unifi_home }}/data:/unifi/data"
            - "{{ unifi_home }}/log:/unifi/log"
            - "{{ private_domain_cert }}:/unifi/cert/cert.pem:ro"
            - "{{ private_domain_key }}:/unifi/cert/privkey.pem:ro"
            - "/etc/timezone:/etc/timezone:ro"
          environment:
            - "RUNAS_UID0=false"
            - "UNIFI_UID={{ defaultuser.uid }}"
            - "UNIFI_GID={{ defaultuser.maingid }}"
            - "CERT_IS_CHAIN=true"
      networks:
        homelan:
          external:
            name: "{{ bridgenetworks.homelan.name }}"
