---
- name: check if MergerFS is installed (changed=not)
  command: dpkg-query -W mergerfs
  register: mergerfs_installed
  failed_when: mergerfs_installed.rc > 1
  changed_when: mergerfs_installed.rc == 1

- name: install MergerFS
  include_tasks: "{{ 'build-src.yml' if install_mergerfs_from_source else 'download-latest.yml' }}"
  when: force_update or mergerfs_installed is changed

- name: check if mergerfs-tools is installed (changed=not)
  stat: path=/usr/bin/mergerfs.balance
  register: mfst_installed
  changed_when: not mfst_installed.stat.exists

- name: install mergerfs-tools
  import_tasks: install-mergerfs-tools.yml
  when: force_update or mfst_installed is changed
