---
- name: check if MergerFS is installed (changed=not)
  command: dpkg-query -W mergerfs
  register: pkg_check
  failed_when: pkg_check.rc > 1
  changed_when: pkg_check.rc == 1

- name: install MergerFS
  include_tasks: "{{ 'build-src.yml' if install_from_source else 'download-latest.yml' }}"
  when: pkg_check|changed

- name: check if mergerfs-tools is installed (changed=not)
  stat: path=/usr/bin/mergerfs.balance
  register: mfst_installed
  changed_when: not mfst_installed.stat.exists

- name: install mergerfs-tools
  import_tasks: install-mergerfs-tools.yml
  when: mfst_installed|changed
