---
- set_fact:
    apphome: "{{appdata}}/kodi-alexa"

- name: Create kodi-alexa appdata directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

- name: Install kodi-alexa config
  copy:
    src: kodi.config
    dest: "{{apphome}}/kodi.config"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755

- name: Start docker app kodi-alexa-skillhost
  docker_service:
    project_name: kodi-alexa-skillhost
    state: present
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        kodi-alexa:
          image: caphm/kodi-alexa:snapshot
          container_name: kodi-alexa
          hostname: kodi-alexa
          user: "{{defaultuser.uid}}"
          restart: always
          volumes:
            - "{{apphome}}:/config"
          network_mode: bridge
          ports:
            - "5454:8000"
          environment:
            - GUNICORN_LOGLEVEL=debug
            - VIRTUAL_HOST=kodi.caphm.de
            - "LETSENCRYPT_HOST={{letsencrypt_domains}}"
            - "LETSENCRYPT_EMAIL={{email_address}}"
