---
- name: install packages required for backup
  apt: pkg={{ item }} state=present
  with_items:
    - rsync

- name: install snapraid configuration
  copy:
    src: {{ snapraidconf|basename }}
    dest: "{{ snapraidconf }}"
    owner: root
    group: root
    mode: 0775

#- name: install rsnapshot configuration
#  copy:
#    src: {{ rsnapshotconf|basename }}
#    dest: "{{ rsnapshotconf }}"
#    owner: root
#    group: root
#    mode: 0775

- name: clone snapraid-runner
  git:
    repo: https://github.com/Chronial/snapraid-runner.git
    dest: /opt/snapraid-runner

- name: install snapraid-runner configuration
  template:
    src: snapraid-runner.conf.j2
    dest: "{{ snap_run_conf }}"
    owner: root
    group: root
    mode: 0775

#- name: install rsnapshot config
#  template:
#    src: "opt/snapraid-runner.j2"
#    dest: "{{ snap_run_conf }}"

- name: setup cron for rsnapshot and snapraid
  cron:
    user: "root"
    job: "{{ item.job }}"
    name: "snapshot-{{ item.name }}"
    weekday: "{{ item.weekday }}"
    minute: "00"
    hour: "{{ item.hour }}"
    dom: "{{ item.dom|default('*') }}"
  with_items:
    - { job: '{{ snap_run_command }}', name: 'snapraid_runner', weekday: '3', hour: '01' }
  tags:
    - cron
