---
- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y
  become: true
  become_user: root
  become_method: sudo

- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - curl
    - exiftool
    - fuse
    - glances
    - git
    - htop
    - iftop
    - iotop
    - jq
    - lynx
    - mc
    - ncdu
    - nmap
    - openssh-server
    - python
    - reptyr
    - screen
    - smartmontools
    - sudo
    - tmux
    - tree
    - wget
  tags:
    - packages

- name: create group for storage
  group:
    name: storage
    state: present
    gid: "{{storagegid}}"

- name: create user caphm
  user:
    name: caphm
    uid: "{{caphmuid}}"
    state: present
    groups: sudo,docker,storage

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  with_items: "{{ mntpoints }}"

- name: mount disks
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{item.opts}}"
    # change to 'mounted' to auto mount
    state: mounted
  with_items: "{{ mounts }}"

- name: create basic folder structure on storage array
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: caphm
    group: storage
    mode: 0775
  with_items: "{{ folders }}"

- name: mount mergerfs array
  mount:
    name: /mnt/storage
    src: /mnt/disk*
    opts: defaults,allow_other,direct_io,use_ino,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    # change to 'mounted' to auto mount
    state: mounted
