---
- name: create docker appdata base directory
  file:
    dest: "{{ appdata }}"
    state: directory
    owner: caphm
    group: caphm

- name: create tmp folder for plex transcoder
  file:
    dest: /tmp/plex-transcode
    state: directory
    owner: caphm
    group: caphm
    mode: 0777

- name: add dtail
  copy:
    src: "usr/bin/dtail"
    dest: "/usr/bin/dtail"
    owner: root
    group: root
    mode: 0777

- name: Create kodi-alexa appdata directory
  file:
    dest: "{{appdata}}/kodi-alexa/"
    state: directory

- name: install kodi-alexa config
  copy:
    src: kodi-alexa/kodi.config
    dest: "{{appdata}}/kodi-alexa/kodi.config"
    owner: "{{caphmuid}}"
    group: "{{caphmgid}}"

- name: copy docker-compose.yml into position
  template:
    src: "docker-compose.yml"
    dest: "{{appdata}}/docker-compose.yml"
    mode: 0755

- name: copy docker-compose-onedrive.yml into position
  template:
    src: "docker-compose-onedrive.yml"
    dest: "{{appdata}}/docker-compose-onedrive.yml"
    mode: 0755

- name: use docker-compose to bring up apps
  shell: "docker-compose -f {{appdata}}/docker-compose.yml up -d"
  when: start_containers
  tags: start_containers

- name: WORKAROUND plex docker /transcode permissions - add container to inventory
  add_host:
    name: plex
    ansible_connection: docker
  changed_when: false
  when: start_containers
  tags: start_containers

- name: WORKAROUND plex docker /transcode permissions - update permissions
  delegate_to: plex
  become: false
  raw: chown plex:plex /transcode
  when: start_containers
  tags: start_containers

- name: Define onedrive services with docker-compose, but don't start them
  shell: "docker-compose -f {{appdata}}/docker-compose-onedrive.yml create"