---
- name: create group for docker appdata
  group:
    name: "{{dockergroup}}"
    state: present
    gid: "{{dockergid}}"

- name: create user for docker appdata
  user:
    name: "{{dockeruser}}"
    shell: /sbin/nologin
    uid: "{{dockeruid}}"
    group: "{{dockergroup}}"

- name: create docker appdata base directory
  file:
    dest: "{{ appdata }}"
    state: directory
    #recurse: yes
    owner: "{{dockeruser}}"
    groups: "{{dockergroup}},storage"

- name: create tmp folder for plex transcoder
  file:
    dest: /tmp/plex-transcode
    state: directory
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"
    mode: 0777

- name: add dtail
  copy:
    src: "usr/bin/dtail"
    dest: "/usr/bin/dtail"
    owner: root
    group: root
    mode: 0777

- name: copy docker-compose.yml into position
  template:
    src: "opt/docker-compose.yml"
    dest: "/opt/docker-compose.yml"
    owner: root
    group: root
    mode: 0775

- name: use docker-compose to bring up apps
  shell: docker-compose -f /opt/docker-compose.yml up -d
  when: start_containers
  tags: start_containers
