---
- name: create group for docker appdata
  group:
    name: "{{dockergroup}}"
    state: present
    gid: "{{dockergid}}"

- name: create user for docker appdata
  user:
    name: "{{dockeruser}}"
    shell: /sbin/nologin
    uid: "{{dockeruid}}"
    groups: "{{dockergroup}},storage"

- name: create docker appdata base directory
  file:
    dest: "{{ appdata }}"
    state: directory
    #recurse: yes
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"

- name: create tmp folder for plex transcoder
  file:
    dest: /tmp/plex-transcode
    state: directory
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"
    mode: 0777

- name: add dtail
  copy:
    src: "usr/bin/dtail"
    dest: "/usr/bin/dtail"
    owner: root
    group: root
    mode: 0777

- name: copy docker-compose.yml into position
  template:
    src: "home/docker/docker-compose.yml"
    dest: "/home/docker/docker-compose.yml"
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"
    mode: 0755

- name: copy docker-compose-onedrive.yml into position
  template:
    src: "home/docker/docker-compose-onedrive.yml"
    dest: "/home/docker/docker-compose-onedrive.yml"
    owner: "{{dockeruser}}"
    group: "{{dockergroup}}"
    mode: 0755

- name: use docker-compose to bring up apps
  shell: docker-compose -f /home/docker/docker-compose.yml up -d
  when: start_containers
  tags: start_containers

- name: WORKAROUND plex docker /transcode permissions - add container to inventory
  add_host:
    name: plex
    ansible_connection: docker
  changed_when: false
  when: start_containers
  tags: start_containers

- name: WORKAROUND plex docker /transcode permissions - update permissions
  delegate_to: plex
  become: false
  raw: chown plex:plex /transcode
  when: start_containers
  tags: start_containers

- name: Define onedrive services with docker-compose, but don't start them
  shell: docker-compose -f /home/docker/docker-compose-onedrive.yml create