---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - cups
  notify:
    - restart cups service

- name: listen on all interfaces
  lineinfile:
    dest: /etc/default/grub
    regexp: "^Listen localhost:631"
    line: "Listen 0.0.0.0:631"
  become: true
  notify: restart cups service

- name: make configuration accessible over network
  become: true
  blockinfile:
    dest: /etc/modprobe.d/blacklist.conf
    backup: yes
    block: |
      # Restrict access to the server...
      <Location />
        Order allow,deny
        Allow @LOCAL
      </Location>

      # Restrict access to the admin pages...
      <Location /admin>
        Order allow,deny
        Allow @LOCAL
      </Location>
  notify:
    - restart cups service

- name: Enable CUPS service on startup
  service:
    name: cups
    state: started
    enabled: yes
