---
- name: Install CUPS
  apt:
    name: cups
    state: "{{ 'latest' if force_update else 'present'}}"
    update_cache: yes
  notify:
    - restart cups service

- name: make CUPS accessible over network
  become: true
  blockinfile:
    dest: /etc/cups/cupsd.conf
    backup: yes
    block: |
      # Listen on all interfaces
      Listen 0.0.0.0:631

      # Restrict access to the server...
      <Location />
        Order allow,deny
        Allow @LOCAL
      </Location>

      # Restrict access to the admin pages...
      <Location /admin>
        Order allow,deny
        Allow @LOCAL
      </Location>
  notify:
    - restart cups service

- name: Enable CUPS service on startup
  service:
    name: cups
    state: started
    enabled: yes
