---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - cups
  notify:
    - restart cups service

- name: Enable CUPS service on startup
  service:
    name: cups
    state: started
    enabled: yes
