---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - cups
  notify:
    - restart cups service

- name: copy cups configuration into position
  copy:
    src: "cupsd.conf"
    dest: "/etc/cups/cupsd.conf"
    backup: yes
  notify:
    - restart cups service

- name: Enable CUPS service on startup
  service:
    name: cups
    state: started
    enabled: yes
