---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - cups
  notify:
    - restart cups service

- name: make configuration accessible over network
  become: true
  blockinfile:
    dest: /etc/cups/cupsd.conf
    backup: yes
    block: |
      # Listen on all interfaces
      Listen 0.0.0.0:631

      # Restrict access to the server...
      <Location />
        Order allow,deny
        Allow @LOCAL
      </Location>

      # Restrict access to the admin pages...
      <Location /admin>
        Order allow,deny
        Allow @LOCAL
      </Location>
  notify:
    - restart cups service

- name: Enable CUPS service on startup
  service:
    name: cups
    state: started
    enabled: yes
