---
- name: update-grub
  command: update-grub
  become: true

- name: update-initramfs
  command: update-initramfs -u
  become: true

- name: reload-apparmor
  command: systemctl reload apparmor.service
  become: true

- name: reload-sysctl
  command: sysctl --system
  become: true