---
# SnapRAID from source, built in a Docker container

- name: install packages required for snapraid
  apt:
    name: rsync
    state: "{{ 'latest' if force_update else 'present' }}"

- name: check if snapraid is installed (changed=not)
  command: dpkg-query -W snapraid
  register: snapraid_installed
  failed_when: snapraid_installed.rc > 1
  changed_when: snapraid_installed.rc == 1

- name: build snapraid from source in a container
  import_tasks: build-src.yml
  when: force_update or snapraid_installed is changed

- name: install snapraid configuration
  copy:
    src: "{{ snapraidconf|basename }}"
    dest: "{{ snapraidconf }}"
    owner: root
    group: root
    mode: 0644

- name: clone snapraid-runner
  git:
    repo: https://github.com/Chronial/snapraid-runner.git
    dest: /opt/snapraid-runner

- name: install snapraid-runner configuration
  template:
    src: snapraid-runner.conf.j2
    dest: "{{ snap_run_conf }}"
    owner: root
    group: root
    mode: 0644

- name: setup cron for snapraid
  cron:
    user: "root"
    job: "{{ item.job }}"
    name: "snapshot-{{ item.name }}"
    weekday: "{{ item.weekday }}"
    minute: "00"
    hour: "{{ item.hour }}"
    dom: "{{ item.dom|default('*') }}"
  loop:
    - { job: '{{ snap_run_command }}', name: 'snapraid_runner', weekday: '3', hour: '01' }
  tags:
    - cron
