---
- name: Create appdata directory
  file:
    dest: "{{item}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  loop:
    - "{{mosquitto_home}}"
    - "{{mosquitto_home}}/certs"

- name: Put root CA certificate in place
  get_url:
    url: https://letsencrypt.org/certs/isrgrootx1.pem.txt
    dest: "{{mosquitto_home}}/certs/cacert.pem"

- name: Install configuration files
  copy:
    src: "{{item}}"
    dest: "{{mosquitto_home}}/{{item}}"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0644
  with_items:
    - mosquitto.conf

- name: Start docker app mosquitto
  docker_service:
    project_name: mosquitto
    state: present
    pull: "{{force_update}}"
    definition:
      version: '3.5'
      services:
        hass-relay:
          image: eclipse-mosquitto
          container_name: mosquitto
          hostname: mosquitto
          stdin_open: true
          tty: true
          user: "{{defaultuser.uid}}:{{defaultuser.maingid}}"
          restart: always
          volumes:
            - "{{mosquitto_home}}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
            - "{{mosquitto_home}}/passwd:/mosquitto/passwd:ro"
            - "{{mosquitto_home}}/data:/mosquitto/data"
            - "{{mosquitto_home}}/log:/mosquitto/log"
            - "{{mosquitto_home}}/certs/cacert.pem:/mosquitto/certs/cacert.pem:ro"
            - "{{certs_root}}/caphm.de.crt:/mosquitto/certs/cert.pem:ro"
            - "{{certs_root}}/caphm.de.key:/mosquitto/certs/key.pem:ro"
          networks:
            - iot
          ports:
            - "1883:1883"
            - "8883:8883"
            - "8884:8884"
          environment:
            - TZ=Europe/Berlin
      networks:
        iot:
          external:
            name: iot
