---
- set_fact:
    apphome: "{{appdata}}/mosquitto"
    certs: "{{apphome}}/certs"
    certs_root: "{{appdata}}/nginx-reverse-proxy/certs"

- name: Create appdata directory
  file:
    dest: "{{item}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - "{{apphome}}"
    - "{{certs}}"

- name: Create symlinks to certificates
  file:
    src: "{{certs_root}}/{{item.target}}"
    dest: "{{certs}}/{{item.link}}"
    state: link
  with_items:
    - { target: "caphm.de.chain.pem", link: "ca.pem" }
    - { target: "caphm.de.crt", link: "cert.pem" }
    - { target: "caphm.de.key", link: "key.pem" }

- name: Install configuration files
  copy:
    src: "{{item}}"
    dest: "{{apphome}}/{{item}}"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0644
  with_items:
    - mosquitto.conf

- name: Start docker app mosquitto
  docker_service:
    project_name: mosquitto
    state: present
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        hass-relay:
          image: eclipse-mosquitto
          container_name: mosquitto
          hostname: mosquitto
          user: "{{defaultuser.uid}}:{{defaultuser.maingid}}"
          restart: always
          volumes:
            - "{{apphome}}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
            - "{{apphome}}/passwd:/mosquitto/passwd:ro"
            - "{{apphome}}/data:/mosquitto/data"
            - "{{apphome}}/log:/mosquitto/log"
            - "{{apphome}}/certs:/mosquitto/certs"
          network_mode: bridge
          ports:
            - "1883:1883"
            - "8883:8883"
            - "8884:8884"
            - "9001:9001"
          environment:
            - TZ=Europe/Berlin
