- name: Create kodi-alexa appdata directory
  file:
    dest: "{{ kodi_alexa_home }}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755

- name: Install kodi-alexa config
  copy:
    src: kodi.config
    dest: "{{ kodi_alexa_home }}/kodi.config"
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"
    mode: 0755

- name: Start docker app kodi-alexa
  docker_service:
    project_name: kodi-alexa
    state: present
    pull: "{{ force_update }}"
    definition:
      version: '3'
      services:
        kodi-alexa:
          image: caphm/kodi-alexa:snapshot
          container_name: kodi-alexa
          hostname: kodi-alexa
          stdin_open: true
          tty: true
          user: "{{ defaultuser.uid }}"
          restart: always
          volumes:
            - "{{ kodi_alexa_home }}:/config"
            - "/etc/timezone:/etc/timezone:ro"
          networks:
            - web
          environment:
            - GUNICORN_LOGLEVEL=debug
          labels:
            traefik.enable: "true"
            traefik.frontend.rule: "Host:{{ kodi_alexa_url }}"
            traefik.docker.network: "web"
            traefik.port: "8080"

      networks:
        web:
          external:
            name: web
