---
- set_fact:
    apphome: "{{appdata}}/teamspeak"

- name: Create teamspeak-server appdata directory
  file:
    dest: "{{apphome}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

- name: Start docker app teamspeak-server
  docker_service:
    project_name: teamspeak-server
    state: present
    pull: "{{update_dockers}}"
    definition:
      version: '2'
      services:
        teamspeak:
          image: aheil/teamspeak3-server
          container_name: teamspeak
          hostname: teamspeak
          restart: always
          volumes:
            - "{{apphome}}:/data"
          network_mode: bridge
          ports:
            - "9987:9987/udp"
            - "10011:10011"
            - "30033:30033"
  register: startup_output

- debug:
    var: startup_output
