---
version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex
    volumes:
      - /home/docker/appdata/plex:/config
      - /tmp/plex-transcode:/transcode
      - /mnt/storage/media:/library
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM
      - PLEX_UID={{dockeruid}}
      - PLEX_GID={{dockergid}}
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - TZ="Europe/Berlin"
      - ALLOWED_NETWORKS="192.168.1.0/24"

  filebot:
    image: rednoah/filebot:node
    container_name: filebot
    hostname: filebot
    volumes:
      - /home/docker/appdata/filebot:/data
      - /mnt/storage/downloads:/download
      - /mnt/storage/media:/out
    network_mode: bridge
    ports:
      - "5452:5452"
    restart: always

  jdownloader:
    image: aptalca/docker-jdownloader2
    container_name: jdownloader
    hostname: jdownloader
    volumes:
      - /home/docker/appdata/jdownloader:/config
      - /mnt/storage/downloads:/download
    network_mode: bridge
    ports:
      - "5453:8080"
    restart: always
    environment:
      - WIDTH=1280
      - HEIGHT=720
      - TZ=Europe/Berlin
      - USER_ID={{dockeruid}}
      - GROUP_ID={{dockergid}}

{% for od in onedrives %}
  {{od.name}}:
    image: caphm/onedrive:latest
    container_name: {{od.name}}
    hostname: {{od.name}}
    volumes:
      - {{od.configdir}}:/config
      - {{od.destdir}}:/onedrive
    network_mode: host
    restart: on-failure
    environment:
      - ONEDRIVE_UID={{od.uid}}
      - ONEDRIVE_GID={{od.gid}}
{% endfor %}
