---
version: '3'
services:
  plex:
    image: plexinc/pms-docker:public
    container_name: plex
    hostname: plex
    volumes:
      - /home/docker/appdata/plex:/config
      - /tmp/plex-transcode:/transcode
      - /mnt/storage/media:/library
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM
      - PLEX_UID={{dockeruid}}
      - PLEX_GID={{dockergid}}
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - TZ="Europe/Berlin"
      - ALLOWED_NETWORKS="192.168.1.0/24"

  filebot:
    image: rednoah/filebot:node
    container_name: filebot
    hostname: filebot
    volumes:
      - /home/docker/appdata/filebot:/data
      - /mnt/storage/downloads:/download
      - /mnt/storage/media:/out
    network_mode: bridge
    ports:
      - "5452:5452"
    restart: always

  jdownloader:
    image: aptalca/docker-jdownloader2
    container_name: jdownloader
    hostname: jdownloader
    volumes:
      - /home/docker/appdata/jdownloader:/config
      - /mnt/storage/downloads:/download
    network_mode: bridge
    ports:
      - "5453:8080"
    restart: always
    environment:
      - WIDTH=1280
      - HEIGHT=720
      - TZ=Europe/Berlin
      - USER_ID={{dockeruid}}
      - GROUP_ID={{dockergid}}

  kodi-alexa:
    image: caphm/kodi-alexa:snapshot
    container_name: kodi-alexa
    hostname: kodi-alexa
    volumes:
      - /home/docker/appdata/kodi-alexa:/config
    network_mode: bridge
    ports:
      - "5454:8000"
    restart: on-failure
    environment:
      - LOGLEVEL=info
      - CERT_SUBJ="/C=DE/O=caphm.de/OU=caphm.de/CN=caphm.de"
      - CERT_VALIDITY=365
