- name: create mount points
  file:
    dest: "{{mountroot}}/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop: "{{ mounts|flatten(levels=1) }}"

- name: mount disks
  mount:
    name: "{{mountroot}}/{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{item.opts}}"
    state: mounted
  loop: "{{ mounts|flatten(levels=1) }}"

- name: create basic folder structure on storage array
  file:
    dest: "{{mountroot}}/{{ item }}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0775
  loop: "{{ folders(levels=1) }}"

################################################################################
# samba
################################################################################
- name: install samba
  apt:
    pkg: samba
    state: present
  notify:
    - start samba service

- name: create spool folder
  file:
    dest: /var/spool/samba/
    state: directory
    mode: 0777

  # TODO: Auto configuring smb.conf based on
  # https://github.com/debops/ansible-samba/blob/master/defaults/main.yml
- name: install samba config
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify:
    - restart samba service

################################################################################
# nfs
################################################################################
# - name: install nfs
#   apt:
#     pkg: nfs-kernel-server
#     state: present
#   notify:
#     - start nfs service

# - name: install nfs config
#   copy:
#     src: exports
#     dest: /etc/exports
#     owner: root
#     group: root
#   notify:
#     - exportfs
#     - restart nfs service
