---
- name: Install prerequisite packages
  apt:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ docker_prerequisite_packages_Ubuntu }}"

- name: Import Docker CE repository gpg key
  apt_key:
    url: "{{ apt_key_url }}"
    state: present
    id: "{{ apt_key_sig }}"
  register: add_repository_key
  ignore_errors: true

- name: Add Docker CE repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
  notify:
    - systemd daemon-reload
    - restart docker service

- name: Enable Docker CE service on startup
  service:
    name: docker
    state: started
    enabled: yes
