- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_home }}"
    state: directory
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_home }}/acme.json"
    state: touch
    mode: 0600

- name: Adding traefik.toml file
  template:
    src: traefik.toml.j2
    dest: "{{ traefik_home }}/traefik.toml"
    mode: 0600

# - name: Create the web network
#   docker_network:
#     name: web

- name: Create the traefik service
  docker_service:
    project_name: traefik
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        traefik:
          image: traefik:alpine
          container_name: traefik
          hostname: traefik
          stdin_open: true
          tty: true
          restart: always
          networks:
            web:
              ipv4_address: 172.18.0.2
          ports:
            - "80:80"
            - "443:443"
            - "8888:8888"
          volumes:
            - "{{ traefik_home }}/traefik.toml:/etc/traefik/traefik.toml"
            - "{{ traefik_home }}/acme.json:/acme.json"
            - /var/run/docker.sock:/var/run/docker.sock
          environment:
            - "TZ=Europe/Berlin"
            - "CF_API_EMAIL={{email_address}}"
            - "CF_API_KEY={{cf_api_key}}"
          labels:
            traefik.frontend.rule: "Host:{{ docker_host }};PathPrefixStrip:/traefik"
            traefik.docker.network: "web"
            traefik.port: "8888"
            traefik.enable: "true"
            traefik.frontend.headers.SSLRedirect: "true"
            traefik.frontend.headers.STSSeconds: 315360000"
            traefik.frontend.headers.browserXSSFilter: "true"
            traefik.frontend.headers.contentTypeNosniff: "true"
            traefik.frontend.headers.forceSTSHeader: "true"
            traefik.frontend.headers.SSLHost: "caphm.de"
            traefik.frontend.headers.STSIncludeSubdomains: "true"
            traefik.frontend.headers.STSPreload: "true"
            traefik.frontend.headers.frameDeny: "true"
      networks:
        web:
          name: web
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.18.0.0/24
