- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_home }}"
    state: directory
    owner: "{{ defaultuser.uid }}"
    group: "{{ defaultuser.maingid }}"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_home }}/acme.json"
    state: touch
    mode: 0600

- name: Adding traefik.toml file
  template:
    src: traefik.toml.j2
    dest: "{{ traefik_home }}/traefik.toml"
    mode: 0600

# - name: Create the traefik_proxy network
#   docker_network:
#     name: traefik_proxy

- name: Create the traefik service
  docker_service:
    project_name: traefik
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        traefik:
          image: traefik
          container_name: traefik
          hostname: traefik
          stdin_open: true
          tty: true
          restart: always
          networks:
            traefik_proxy:
              ipv4_address: 172.18.0.2
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - "{{ traefik_home }}/traefik.toml:/etc/traefik/traefik.toml"
            - "{{ traefik_home }}/acme.json:/acme.json"
            - /var/run/docker.sock:/var/run/docker.sock
          labels:
            traefik.frontend.rule: "Host:{{ docker_host }};PathPrefixStrip:/traefik"
            traefik.docker.network: "traefik_proxy"
            traefik.port: "8888"
            traefik.enable: "false"
      networks:
        traefik_proxy:
          name: traefik_proxy
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.18.0.0/24

- name: Start docker app home-assistant
  docker_service:
    project_name: home-assistant-test
    state: present
    pull: "{{force_update}}"
    definition:
      version: "3.5"
      services:
        home-assistant:
          image: homeassistant/home-assistant
          container_name: home-assistant-test
          hostname: home-assistant
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{hass_home}}:/config"
          network_mode: host
          environment:
            - TZ=Europe/Berlin
        hass-relay:
          image: tynor88/socat
          container_name: hass-relay-test
          hostname: home-assistant
          restart: always
          networks:
            - traefik_proxy
            - iot
          environment:
            - LISTEN_PORT=8123
            - FORWARD_PORT=8123
          labels:
            traefik.enable: "true"
            traefik.frontend.rule: "Host:{{ home_assistant_url }}"
            traefik.docker.network: "traefik_proxy"
            traefik.port: "8123"
        appdaemon:
          image: acockburn/appdaemon:latest
          container_name: appdaemon-test
          hostname: appdaemon
          stdin_open: true
          restart: always
          volumes:
            - /etc/localtime:/etc/localtime:ro
            - "{{appdaemon_home}}:/conf"
          networks:
            - iot
          environment:
            - "HA_URL=http://home-assistant:8123"
            - "TOKEN={{appdaemon_token}}"
      networks:
        iot:
          name: iot
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.18.1.0/24
        traefik_proxy:
          external:
            name: traefik_proxy
