---
- set_fact:
    apphome_plex: "{{appdata}}/plex"
    apphome_filebot: "{{appdata}}/filebot"
    apphome_jdownloader: "{{appdata}}/jdownloader"

- name: Create media-server appdata directory
  file:
    dest: "{{item}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  with_items:
    - "{{apphome_plex}}"
    - "{{apphome_filebot}}"
    - "{{apphome_jdownloader}}"

- name: Create folder for Plex transcoder
  file:
    dest: "{{transcode_dir}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0777

- name: Start docker app media-server
  docker_service:
    project_name: media-server
    state: present
    definition:
      version: '2'
      services:
        plex:
          image: plexinc/pms-docker:public
          container_name: plex
          hostname: plex
          restart: on-failure
          volumes:
            - "{{apphome_plex}}:/config"
            - "{{transcode_dir}}:/transcode"
            - "{{arraypath}}/media:/library"
          network_mode: bridge
          ports:
            - "32400:32400/tcp"
            - "1900:1900/udp"
            - "3005:3005/tcp"
            - "5353:5353/udp"
            - "8324:8324/tcp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
            - "32469:32469/tcp"
          environment:
            - "PLEX_CLAIM='{{PLEX_CLAIM_TOKEN}}'"
            - "PLEX_UID={{defaultuser.uid}}"
            - "PLEX_GID={{defaultuser.maingid}}"
            - "ADVERTISE_IP='http://{{ansible_default_ipv4.address}}:32400/'"
            - CHANGE_CONFIG_DIR_OWNERSHIP=false
            - TZ=Europe/Berlin
            - ALLOWED_NETWORKS="192.168.1.0/24"
            - VIRTUAL_HOST=plex.caphm.de
            - VIRTUAL_PORT=32400
            - LETSENCRYPT_HOST=caphm.de,kodi.caphm.de,plex.caphm.de,smarthome.caphm.de
            - "LETSENCRYPT_EMAIL={{email_address}}"

        filebot:
          image: rednoah/filebot:node
          container_name: filebot
          hostname: filebot
          restart: on-failure
          volumes:
            - "{{apphome_filebot}}:/data"
            - "{{arraypath}}/downloads:/download"
            - "{{arraypath}}/media:/out"
          network_mode: bridge
          ports:
            - "5452:5452"

        jdownloader:
          image: aptalca/docker-jdownloader2
          container_name: jdownloader
          hostname: jdownloader
          restart: on-failure
          volumes:
            - "{{apphome_jdownloader}}:/config"
            - "{{arraypath}}/downloads:/download"
          network_mode: bridge
          ports:
            - "5453:8080"
          environment:
            - WIDTH=1280
            - HEIGHT=720
            - TZ=Europe/Berlin
            - "USER_ID={{defaultuser.uid}}"
            - "GROUP_ID={{defaultuser.maingid}}"
  register: startup-output

- debug:
    var: startup-output

- name: WORKAROUND plex docker /transcode permissions - add container to inventory
  add_host:
    name: plex
    ansible_connection: docker
  changed_when: false

- name: WORKAROUND plex docker /transcode permissions - update permissions
  delegate_to: plex
  become: false
  raw: chown plex:plex /transcode