- name: Create media-server appdata directories
  file:
    dest: "{{item}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
  loop:
    - "{{ plex_home }}"
    - "{{ plex_home }}/certs"
    - "{{ plex_transcode }}"
    - "{{ plex_tmp }}"
    - "{{ filebot_home }}"
    - "{{ jdownloader_home }}"

- name: upload the filebot Dockerfile to the docker host
  copy:
    src: "{{item}}"
    dest: "{{filebot_home}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
  loop:
    - Dockerfile
    - filebot-node
  register: filebot_dockerfile

- name: Start docker app media-server
  docker_compose:
    project_name: media-server
    state: present
    build: "{{force_update or filebot_dockerfile.changed}}"
    pull: "{{force_update}}"
    restarted: "{{force_update or filebot_dockerfile.changed}}"
    definition:
      version: '3.5'
      services:
        plex:
          image: plexinc/pms-docker:latest
          container_name: plex
          hostname: plex
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{ plex_home }}:/config"
            - "{{ arraypath }}/media:{{ arraypath }}/media"
            - "{{ plex_transcode }}:/transcode"
            - "{{ plex_tmp }}:/tmp"
            - "/etc/timezone:/etc/timezone:ro"
          networks:
            traefik_backend:
            homelan:
              ipv4_address: "{{ macvlannetworks.homelan.static_ips.plex }}"
          # Uncomment this to enable HW accelerated transcoding (PlexPass required)
          devices:
           - /dev/dri:/dev/dri
          privileged: true
          environment:
            - "PLEX_CLAIM={{ plex_claim_token }}"
            - "PLEX_UID={{ defaultuser.uid }}"
            - "PLEX_GID={{ defaultuser.maingid }}"
            - "ADVERTISE_IP=http://{{ macvlannetworks.homelan.static_ips.plex }}:32400,https://{{ plex_url }}:443"
            - "CHANGE_CONFIG_DIR_OWNERSHIP=true"
            - "ALLOWED_NETWORKS={{ macvlannetworks.homelan.subnet2 }}"
          labels:
            traefik.enable: "true"
            traefik.frontend.rule: "Host:{{ plex_url }}"
            traefik.docker.network: "{{ bridgenetworks.traefik_backend.name }}"
            traefik.port: "32400"

        filebot:
          build: "{{filebot_home}}"
          container_name: filebot
          hostname: filebot
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{filebot_home}}:/data"
            - "{{arraypath}}/downloads:/download"
            - "{{arraypath}}/media:/out"
          networks:
            - traefik_backend
          ports:
            - "5452:5452"
          labels:
            traefik.enable: "false"

        jdownloader:
          image: aptalca/docker-jdownloader2
          container_name: jdownloader
          hostname: jdownloader
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{jdownloader_home}}:/config"
            - "{{arraypath}}/downloads:/download"
          networks:
            - traefik_backend
          environment:
            - WIDTH=1280
            - HEIGHT=720
            - TZ=Europe/Berlin
            - "USER_ID={{defaultuser.uid}}"
            - "GROUP_ID={{defaultuser.maingid}}"
          labels:
            traefik.frontend.rule: "Host:{{ traefik_host }},localhost;PathPrefixStrip:{{jdownloader_path}}"
            traefik.docker.network: "{{ bridgenetworks.traefik_backend.name }}"
            traefik.port: "8080"
            traefik.enable: "true"

        tautulli:
          image: tautulli/tautulli
          container_name: tautulli
          hostname: tautulli
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{ tautulli_home }}:/config"
            - "{{ plex_home }}/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
            - "/etc/timezone:/etc/timezone:ro"
          networks:
            - traefik_backend
          environment:
            - "PUID={{ defaultuser.uid }}"
            - "PGID={{ defaultuser.maingid }}"
          labels:
            traefik.frontend.rule: "Host:{{ traefik_host }},localhost;PathPrefix:{{ tautulli_path }}"
            traefik.docker.network: "{{ bridgenetworks.traefik_backend.name }}"
            traefik.port: "8181"
            traefik.enable: "true"

      networks:
        traefik_backend:
          external:
            name: "{{ bridgenetworks.traefik_backend.name }}"
        homelan:
          external:
            name: "{{ macvlannetworks.homelan.name }}"
