- name: Create media-server appdata directories
  file:
    dest: "{{item}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
  loop:
    - "{{ plex_home }}"
    - "{{ plex_home }}/certs"
    - "{{ plex_transcode }}"
    - "{{ plex_tmp }}"
    - "{{ filebot_home }}"
    - "{{ jdownloader_home }}"

- name: upload the filebot Dockerfile to the docker host
  copy:
    src: "{{item}}"
    dest: "{{filebot_home}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
  loop:
    - Dockerfile
    - filebot-node
  register: filebot_dockerfile

- name: Start docker app media-server
  docker_service:
    project_name: media-server
    state: present
    build: "{{force_update or filebot_dockerfile.changed}}"
    pull: "{{force_update}}"
    restarted: "{{force_update or filebot_dockerfile.changed}}"
    definition:
      version: '3.5'
      services:
        plex:
          image: plexinc/pms-docker:latest
          container_name: plex
          hostname: plex
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{ plex_home }}:/config"
            - "{{ arraypath }}/media:{{ arraypath }}/media"
            - "{{ plex_transcode }}:/transcode"
            - "{{ plex_tmp }}:/tmp"
            - "/etc/timezone:/etc/timezone:ro"
          networks:
            web:
              ipv4_address: "{{ macvlannetworks.web.static_ips.plex }}"
          dns: "{{ macvlannetworks.web.dns_server }}"
          environment:
            - "PLEX_CLAIM={{ plex_claim_token }}"
            - "PLEX_UID={{ defaultuser.uid }}"
            - "PLEX_GID={{ defaultuser.maingid }}"
            - "ADVERTISE_IP=https://{{ plex_url }}"
            - "CHANGE_CONFIG_DIR_OWNERSHIP=false"
            - "ALLOWED_NETWORKS={{ ansible_default_ipv4.address }}/24"
          labels:
            traefik.enable: "true"
            traefik.frontend.rule: "Host:{{ plex_url }}"
            traefik.docker.network: "{{ macvlannetworks.web.name }}"
            traefik.port: "32400"

        filebot:
          build: "{{filebot_home}}"
          container_name: filebot
          hostname: filebot
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{filebot_home}}:/data"
            - "{{arraypath}}/downloads:/download"
            - "{{arraypath}}/media:/out"
          networks:
            web:
              ipv4_address: "{{ macvlannetworks.web.static_ips.filebot }}"
          dns: "{{ macvlannetworks.web.dns_server }}"
          labels:
            traefik.enable: "false"

        jdownloader:
          image: aptalca/docker-jdownloader2
          container_name: jdownloader
          hostname: jdownloader
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{jdownloader_home}}:/config"
            - "{{arraypath}}/downloads:/download"
          networks:
            - web
          dns: "{{ macvlannetworks.web.dns_server }}"
          environment:
            - WIDTH=1280
            - HEIGHT=720
            - TZ=Europe/Berlin
            - "USER_ID={{defaultuser.uid}}"
            - "GROUP_ID={{defaultuser.maingid}}"
          labels:
            traefik.fqdn.frontend.rule: "Host:srv.caphm.de;PathPrefixStrip:{{jdownloader_path}}"
            traefik.local.frontend.rule: "Host:localhost;PathPrefixStrip:{{jdownloader_path}}"
            traefik.docker.network: "{{ macvlannetworks.web.name }}"
            traefik.port: "8080"
            traefik.enable: "true"

        tautulli:
          image: tautulli/tautulli
          container_name: tautulli
          hostname: tautulli
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{ tautulli_home }}:/config"
            - "{{ plex_home }}/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
            - "/etc/timezone:/etc/timezone:ro"
          networks:
            - web
          environment:
            - "PUID={{ defaultuser.uid }}"
            - "PGID={{ defaultuser.maingid }}"
          labels:
            traefik.fqdn.frontend.rule: "Host:srv.caphm.de;PathPrefix:{{ tautulli_path }}"
            traefik.local.frontend.rule: "Host:localhost;PathPrefix:{{ tautulli_path }}"
            traefik.docker.network: "{{ macvlannetworks.web.name }}"
            traefik.port: "8181"
            traefik.enable: "true"

      networks:
        web:
          external:
            name: "{{ macvlannetworks.web.name }}"
