---
- name: Create media-server appdata directory
  file:
    dest: "{{item}}"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
  loop:
    - "{{apphome_plex}}"
    - "{{apphome_filebot}}"
    - "{{apphome_jdownloader}}"

- name: upload the filebot Dockerfile to the docker host
  copy:
    src: "{{item}}"
    dest: "{{apphome_filebot}}/"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755
  loop:
    - Dockerfile
    - filebot-node

- name: Start docker app media-server
  docker_service:
    project_name: media-server
    state: present
    build: "{{force_update}}"
    pull: "{{force_update}}"
    definition:
      version: '3.5'
      services:
        plex:
          image: plexinc/pms-docker:latest
          container_name: plex
          hostname: plex
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{apphome_plex}}:/config"
            - "{{arraypath}}/media:/library"
            - "{{arraypath}}/media:{{arraypath}}/media"
          networks:
            - web
          ports:
            - "1900:1900/udp"
            - "3005:3005/tcp"
            - "8324:8324/tcp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
            - "32469:32469/tcp"
          environment:
            - "PLEX_CLAIM={{plex_claim_token}}"
            - "PLEX_UID={{defaultuser.uid}}"
            - "PLEX_GID={{defaultuser.maingid}}"
            - "ADVERTISE_IP=http://{{ansible_default_ipv4.address}}:32400"
            - CHANGE_CONFIG_DIR_OWNERSHIP=false
            - TZ=Europe/Berlin
            - ALLOWED_NETWORKS=192.168.1.0/24
          labels:
            traefik.enable: "true"
            traefik.frontend.rule: "Host:{{ plex_url }}"
            traefik.docker.network: "web"
            traefik.port: "32400"
        filebot:
          build: "{{apphome_filebot}}"
          container_name: filebot
          hostname: filebot
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{apphome_filebot}}:/data"
            - "{{arraypath}}/downloads:/download"
            - "{{arraypath}}/media:/out"
          networks:
            - web
          labels:
            traefik.frontend.rule: "Host:{{ docker_host }};PathPrefixStrip:/filebot"
            traefik.docker.network: "web"
            traefik.port: "5452"
            traefik.enable: "true"

        jdownloader:
          image: aptalca/docker-jdownloader2
          container_name: jdownloader
          hostname: jdownloader
          stdin_open: true
          tty: true
          restart: always
          volumes:
            - "{{apphome_jdownloader}}:/config"
            - "{{arraypath}}/downloads:/download"
          networks:
            - web
          environment:
            - WIDTH=1280
            - HEIGHT=720
            - TZ=Europe/Berlin
            - "USER_ID={{defaultuser.uid}}"
            - "GROUP_ID={{defaultuser.maingid}}"
          labels:
            traefik.frontend.rule: "Host:{{ docker_host }};PathPrefixStrip:/jdownloader"
            traefik.docker.network: "web"
            traefik.port: "8080"
            traefik.enable: "true"
      networks:
        web:
          external:
            name: web

- name: Create folder for plex certificates
  file:
    dest: "{{apphome_plex}}/certs"
    state: directory
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"

- name: Put script to convert Letsencrypt certificate to PKCS12
  template:
    src: convert-certificate.sh
    dest: "{{apphome_plex}}/certs/convert-certificate.sh"
    owner: "{{defaultuser.uid}}"
    group: "{{defaultuser.maingid}}"
    mode: 0755

- name: Add cronjob to convert new certificates automatically
  cron:
    user: "root"
    job: "{{apphome_plex}}/certs/convert-certificate.sh"
    name: "convert-plex-certificate"
    weekday: "*"
    minute: "00"
    hour: "01"
    dom: "*"
