- alias: 'Lichter ausschalten bei Abwesenheit'
  trigger:
    platform: state
    entity_id: group.household_members
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights
