wohnzimmer_licht:
  name: Wohnzimmerlicht
  entities:
    - light.deckenleuchte
    - switch.zauberkugel

# views

default_view:
  view: yes
  icon: mdi:home 
  entities:
    - group.wohnzimmer_licht
    - switch.flux

wohnzimmer:
  name: Wohnzimmer
  view: yes
  entities:
    - group.wohnzimmer_licht
    - sensor.tradfri_remote_control
